export interface Extracurricular {
  no: number;
  id: string;
  name: string;
  category: string;
  day: 'Senin' | 'Selasa' | 'Rabu' | 'Kamis';
  schedule: string;
  desc: string;
  mentor: string;
  image: string;
  tagColor: string;
  badge: string;
}

export const MANDATORY_CLUB = {
  name: 'Gerakan Pramuka (Gugus Depan SMAGRISA)',
  badge: 'Ekstrakurikuler Wajib',
  desc: 'Pendidikan kepramukaan wajib bagi seluruh peserta didik guna membentuk karakter disiplin, kemandirian, kepemimpinan, keterampilan bertahan hidup, dan jiwa gotong royong.',
  schedule: 'Jumat, 13.30 - 15.00 WIB',
  mentor: 'Mabigus & Pembina Pramuka SMAGRISA',
  image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
};

export const ELECTIVE_CLUBS: Extracurricular[] = [
  {
    no: 1,
    id: 'pasgrisa',
    name: 'PASGRISA (Paskibra SMAGRISA)',
    category: 'Kepemimpinan',
    day: 'Senin',
    badge: 'Pasukan Pengibar Bendera',
    desc: 'Melatih kedisiplinan, ketahanan fisik, formasi baris-berbaris (PBB) presisi tinggi, serta seleksi Paskibraka Kabupaten Lumajang.',
    schedule: 'Senin, 15.00 - 16.30 WIB',
    mentor: 'Instruktur Purna Paskibraka',
    image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-red-50 text-red-700 border-red-200',
  },
  {
    no: 2,
    id: 'futsal',
    name: 'FUTSAL',
    category: 'Olahraga',
    day: 'Senin',
    badge: 'Olahraga & Atletik',
    desc: 'Mengasah taktik permainan cepat, kontrol bola, shooting akurat, stamina fisik, dan kekompakan tim dalam turnamen antar-pelajar.',
    schedule: 'Senin, 15.00 - 16.30 WIB',
    mentor: 'Coach Futsal Sekolah',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  {
    no: 3,
    id: 'basket',
    name: 'BASKET',
    category: 'Olahraga',
    day: 'Selasa',
    badge: 'Olahraga & Atletik',
    desc: 'Membina fisik prima, kemampuan dribble, tembakan akurat, pertahanan rapat, dan strategi tim dalam kejuaraan basket pelajar & DBL.',
    schedule: 'Selasa, 15.00 - 16.30 WIB',
    mentor: 'Coach Basket SMAGRISA',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-orange-50 text-orange-700 border-orange-200',
  },
  {
    no: 4,
    id: 'math-club',
    name: 'MATHEMATICS STUDY CLUB',
    category: 'Akademik & Sains',
    day: 'Selasa',
    badge: 'Sains & Olimpiade',
    desc: 'Pendalaman penalaran logika analitis, bedah soal HOTS, dan pembinaan intensif Olimpiade Sains Nasional (OSN) Matematika.',
    schedule: 'Selasa, 15.00 - 16.30 WIB',
    mentor: 'Tim Pembina OSN Matematika',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  {
    no: 5,
    id: 'albanjari',
    name: 'ALBANJARI',
    category: 'Keagamaan',
    day: 'Selasa',
    badge: 'Seni Religi & Sholawat',
    desc: 'Melantunkan sholawat nabi dengan ketukan rebana Al-Banjari yang harmonis serta tampil di festival hadrah dan peringatan hari besar Islam.',
    schedule: 'Selasa, 15.00 - 16.30 WIB',
    mentor: 'Ustadz Pembina Seni Hadrah',
    image: 'https://images.unsplash.com/photo-1585036156171-384164a8c675?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-teal-50 text-teal-700 border-teal-200',
  },
  {
    no: 6,
    id: 'game-sport',
    name: 'GAME SPORT (E-Sport)',
    category: 'Teknologi & Gaming',
    day: 'Selasa',
    badge: 'E-Sport & Strategi Digital',
    desc: 'Pembinaan atlet game digital kompetitif terarah (Mobile Legends, PUBG Mobile) dengan etika digital, komunikasi, dan strategi teamwork.',
    schedule: 'Selasa, 15.00 - 16.30 WIB',
    mentor: 'Instruktur Komunitas E-Sport',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  {
    no: 7,
    id: 'tari',
    name: 'TARI',
    category: 'Seni & Budaya',
    day: 'Rabu',
    badge: 'Seni Tari Tradisional',
    desc: 'Mempelajari wiraga, wirama, dan wirasa tari tradisional Jawa Timur dan kreasi nusantara untuk ajang FLS2N serta seremonial resmi.',
    schedule: 'Rabu, 15.00 - 16.30 WIB',
    mentor: 'Pelatih Seni Tari Tradisional',
    image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-fuchsia-50 text-fuchsia-700 border-fuchsia-200',
  },
  {
    no: 8,
    id: 'volly',
    name: 'VOLLY',
    category: 'Olahraga',
    day: 'Rabu',
    badge: 'Olahraga & Atletik',
    desc: 'Mengasah kekuatan smash, servis presisi, pertahanan passing bawah, dan kerjasama tim dalam liga bola voli pelajar.',
    schedule: 'Rabu, 15.00 - 16.30 WIB',
    mentor: 'Instruktur PBVSI',
    image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  {
    no: 9,
    id: 'pmr',
    name: 'PMR (Palang Merah Remaja)',
    category: 'Kemanusiaan',
    day: 'Rabu',
    badge: 'Kemanusiaan & Medis',
    desc: 'Pelatihan pertolongan pertama pada kecelakaan (PP), evakuasi tandu, perawatan keluarga, donor darah, dan jiwa sukarelawan.',
    schedule: 'Rabu, 15.00 - 16.30 WIB',
    mentor: 'Korps Sukarela PMI',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  {
    no: 10,
    id: 'karawitan',
    name: 'KARAWITAN',
    category: 'Seni & Budaya',
    day: 'Kamis',
    badge: 'Gamelan Jawa Tradisional',
    desc: 'Melestarikan harmoni gamelan slendro & pelog, kepekaan rasa musikal Jawa, serta mengiringi pergelaran seni dan wayang.',
    schedule: 'Kamis, 15.00 - 16.30 WIB',
    mentor: 'Instruktur Sanggar Karawitan',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  {
    no: 11,
    id: 'band',
    name: 'BAND',
    category: 'Seni & Budaya',
    day: 'Kamis',
    badge: 'Musik & Akustik',
    desc: 'Wadah musikalitas vokal, gitar, drum, keyboard, dan bass untuk menyalurkan kreativitas di pentas seni dan festival band pelajar.',
    schedule: 'Kamis, 15.00 - 16.30 WIB',
    mentor: 'Guru Pembina Seni Musik',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  {
    no: 12,
    id: 'english-club',
    name: 'ENGLISH STUDY CLUB',
    category: 'Akademik & Bahasa',
    day: 'Kamis',
    badge: 'Bahasa & Public Speaking',
    desc: 'Meningkatkan kemahiran bahasa Inggris aktif, debat kompetitif, speech contest, storytelling, dan persiapan sertifikasi.',
    schedule: 'Kamis, 15.00 - 16.30 WIB',
    mentor: 'Guru Bahasa Inggris',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-sky-50 text-sky-700 border-sky-200',
  },
  {
    no: 13,
    id: 'pencak-silat',
    name: 'PENCAK SILAT',
    category: 'Olahraga',
    day: 'Kamis',
    badge: 'Bela Diri Tradisional',
    desc: 'Mengembangkan ketahanan fisik, jurus pertahanan diri, filosofi budi pekerti luhur, dan prestasi kejuaraan IPSI / O2SN.',
    schedule: 'Kamis, 15.00 - 16.30 WIB',
    mentor: 'Pendekar Perguruan Silat',
    image: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?q=80&w=800&auto=format&fit=crop',
    tagColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
];

export const DAYS = ['Semua Hari', 'Senin', 'Selasa', 'Rabu', 'Kamis'] as const;
